# Generated by Django 3.0.8 on 2020-09-07 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='list',
            new_name='lists',
        ),
    ]
